### ISSUE TITLE
show live output on of katello-installer command

### ISSUE THREAD

**Issue by johnpmitsch** [RedHatSatellite/satellite-clone#200]
apparently, a task structured like this will show the live output of a command:
```
- name: Run puppet with remote screen
   command: screen -L -h 1000000 -d -m -S {{ inventory_hostname}} ssh -i {{ ansible_ssh_private_key_file }} -t root@{{ ansible_ssh_host }} '{{ puppet_run }}; {{ puppet_post_run }}'
   args:
     chdir: "{{ playbook_dir }}"
   async: True
   poll: 0
   delegate_to: localhost
```
