### ISSUE TITLE
Required space check is calculated incorrectly when there are mounted volumes

### ISSUE THREAD

**Issue by sthirugn** [RedHatSatellite/satellite-clone#286]
Code in pre_install_check.yml:
```
- name: find root partition's free space
  set_fact:
    root_free_space: "{{ (item.size_available | int) / 1000000000 }}"
    cacheable: true
  when: item.mount == "/"
  with_items: "{{ hostvars[inventory_hostname] ['ansible_mounts'] }}"
```
The above logic ignores the mounted volume space so an error is thrown although the user has enough space on the mounted volumes.

Sample file system where this check failed:
```
$ df -h
Filesystem                          Size  Used Avail Use% Mounted on
/dev/mapper/root_vg-root_lv         2.0G   74M  2.0G   4% /
/dev/mapper/root_vg-usr_lv          6.0G  2.1G  4.0G  35% /usr
/dev/mapper/root_vg-home_lv         2.0G   33M  2.0G   2% /home
/dev/mapper/root_vg-var_lv          6.0G  2.2G  3.9G  36% /var
/dev/mapper/data_vg-rhsatVarLib_lv  800G  184M  800G   1% /var/lib
```
